- name: ansible-clickhouse
  src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  #version: 1.13
- name: vector_role
  src: https://github.com/AleksTurbo/vector-role.git
  scm: git
- name: lighthouse_role
  src: https://github.com/AleksTurbo/lighthouse-role.git
  scm: git